// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eckfvknzfqpfuleqwewg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVja2Z2a256ZnFwZnVsZXF3ZXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwMjA4NjcsImV4cCI6MjA4NzU5Njg2N30.D448-tCP4zR35et4-XikXCApAstaVYLOCynqfqKVL10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});